### ISSUE TITLE
Can not use in IDA8 python3.6

### ISSUE THREAD

**Issue by hac425xxx** [patois/HRDevHelper#9]
log

```
D:\soft\IDA8\plugins\hrdevhelper.py: module 'hrdh' has no attribute 'handler'
Traceback (most recent call last):
  File "D:\soft\IDA8\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript
    exec(code, g)
  File "D:/soft/IDA8/plugins/hrdevhelper.py", line 10, in <module>
    import hrdh.handler as handler
  File "D:/soft/IDA8/plugins\hrdh\handler.py", line 7, in <module>
    from hrdevhelper import HRDevHelper
  File "D:/soft/IDA8/plugins\hrdevhelper.py", line 10, in <module>
    import hrdh.handler as handler
AttributeError: module 'hrdh' has no attribute 'handler'
```

**Comment by patois** [comment]
I am unable to reproduce on IDA 8.0, Python 3.10.3. Could you provide more detail please?

**Comment by stevemk14ebr** [comment]
I can confirm the plugin works fine on IDA 8.2 with python 3.10+
